<?php

/*
 * This file is part of the Assetic package, an OpenSky project.
 *
 * (c) 2010-2012 OpenSky Project Inc
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Assetic\Test\Filter;

use Assetic\Asset\StringAsset;
use Assetic\Filter\DartFilter;

/**
 * @group integration
 */
class DartFilterTest extends \PHPUnit_Framework_TestCase
{
    private $filter;

    protected function setUp()
    {
        if (!isset($_SERVER['DART2JS']) || !isset($_SERVER['DART2JS'])) {
            $this->markTestSkipped('There is no DART2JS environment variable.');
        }

        $this->filter = new DartFilter($_SERVER['DART2JS']);
    }

    public function testFilterLoad()
    {
        $expected = "Generated by dart2js, the Dart to JavaScript compiler.";

        $asset = new StringAsset("import 'dart:html';
                                    main() {
                                      var msg = query('#msg');
                                      var btn = new ButtonElement();
                                      btn.text = 'Click me!';
                                      btn.on.click.add((e) => msg.text = 'Dart!');
                                      document.body.nodes.add(btn);
                                    }");
        $asset->load();

        $this->filter->filterLoad($asset);

        $this->assertContains($expected, $asset->getContent());
    }
}
